plugins {
    id 'java'
    id 'application'
}

mainClassName = 'uk.finlaysmith.stubby.SergeantStubby'
group = 'uk.finlaysmith.stubby'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = mainClassName
}

repositories {
    // If you ever add external dependencies from Maven
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'lib', include: ['*.jar'])
}
